development:
  adapter: mysql
  encoding: utf8
  database: admin_scaffold
  username: root
  password:
  socket:  /opt/local/var/run/mysql5/mysqld.sock


test:
  adapter: mysql
  encoding: utf8
  database: admin_scaffold_test
  username: root
  password:
  socket:  /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: admin_scaffold
  username: root
  password: 
  socket:  /opt/local/var/run/mysql5/mysqld.sock
